config/routes.rb
Hydra::Application.routes.draw do
  namespace :admin do
    root :to => 'pages#index'
    resources :domains
    resources :sites
    resources :pages
  end
  get "admin/documents" => "admin/documents#index"
  post "admin/documents/mkdir" => "admin/documents#mkdir"
  post "admin/documents/delete" => "admin/documents#delete"
  post "admin/documents/upload" => "admin/documents#upload"

  get "page/index"

  get "page/error"

  devise_for :users do
    get "/login" => "devise/sessions#new"
    get '/logout', :to => 'devise/sessions#destroy'
    get '/register', :to => 'devise/users#new'
  end
  

  root :to => "page#index"
  
  get "(:page)", :to => "page#index"

end

app/views/admin/pages/_form.html.erb
<%= form_for([:admin, @page]) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>name: <%= f.text_field :name %></div>
  <div>title: <%= f.text_field :title %></div>
  <div>data: <%= f.text_area :data, :class => "ckeditor" %></div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @page] %> |
<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>name</th>
    <th>actions</th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.name %></td>
    <td><%= link_to 'Show', [:admin, page] %> |
        <%= link_to 'Edit', edit_admin_page_path(page) %> |
        <%= link_to 'Destroy', [:admin, page], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_admin_page_path %>

app/views/admin/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/show.html.erb
<p id="notice"><%= notice %></p>
<% @title = @page.title %>
<div>
<%=raw @page.data %>
</div>
<p>
<%= link_to 'Edit', edit_admin_page_path(@page) %> |
<%= link_to 'Back', admin_pages_path %>
</p>