config/routes.rb
Hydra::Application.routes.draw do
  namespace :admin do
    root :to => 'pages#index'
    resources :domains
    resources :sites
    resources :pages
  end
  get "admin/documents" => "admin/documents#index"
  post "admin/documents/mkdir" => "admin/documents#mkdir"
  post "admin/documents/delete" => "admin/documents#delete"
  post "admin/documents/upload" => "admin/documents#upload"

  get "page/index"

  get "page/error"

  devise_for :users do
    get "/login" => "devise/sessions#new"
    get '/logout', :to => 'devise/sessions#destroy'
    get '/register', :to => 'devise/users#new'
  end
  

  root :to => "page#index"
  
  get "(:page)", :to => "page#index"

end

app/models/domain.rb
class Domain < ActiveRecord::Base
  belongs_to :site
  default_scope where(:active => true)
  
  def name=(value)
    self[:name] = value.downcase
  end
  
  def to_backup_hash
    backup_hash = { }
    col_names = Domain.column_names - ["id", "site_id"]
    col_names.each { |col| backup_hash[col] = self.send(col.to_sym ) }
    backup_hash
  end
  
  def self.from_backup_hash(backup_hash, site_id)
    domain = Domain.new(backup_hash)
    domain.site_id = site_id
    if domain.save
      return domain
    else
      raise RuntimeError, "Unable to read/save Domain #{domain.inspect}"
    end
  end
end

app/controllers/admin/domains_controller.rb
class Admin::DomainsController < ApplicationController
  before_filter :requires_site_admin_login
  
  # GET /domains
  # GET /domains.xml
  def index
    @domains = Domain.all

    respond_to do |format|
      format.html # index.html.erb
   #   format.xml  { render :xml => @domains }
    end
  end

  # GET /domains/1
  # GET /domains/1.xml
  def show
    @domain = Domain.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
   #   format.xml  { render :xml => @domain }
    end
  end

  # GET /domains/new
  # GET /domains/new.xml
  def new
    @domain = Domain.new
    @site_select = current_user.all_sites_select
    
    respond_to do |format|
      format.html # new.html.erb
   #   format.xml  { render :xml => @domain }
    end
  end

  # GET /domains/1/edit
  def edit
    @domain = Domain.find(params[:id])
    @site_select = current_user.all_sites_select
  end

  # POST /domains
  # POST /domains.xml
  def create
    params[:domain][:site_id] ||= uber_page_site.id
    @domain = Domain.new(params[:domain])
    
    respond_to do |format|
      if @domain.save
        format.html { redirect_to([:admin, @domain], :notice => 'Domain was successfully created.') }
     #   format.xml  { render :xml => @domain, :status => :created, :location => @domain }
      else
        format.html { render :action => "new" }
     #   format.xml  { render :xml => @domain.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /domains/1
  # PUT /domains/1.xml
  def update
    @domain = Domain.find(params[:id])
    puts params.inspect
    puts @domain.inspect
    params[:domain][:site_id] ||= uber_page_site.id
    respond_to do |format|
      if @domain.update_attributes(params[:domain])
        puts "----"
        puts @domain.inspect
        format.html { redirect_to([:admin, @domain], :notice => 'Domain was successfully updated.') }
      #  format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
     #   format.xml  { render :xml => @domain.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.xml
  def destroy
    @domain = Domain.find(params[:id])
    @domain.destroy

    respond_to do |format|
      format.html { redirect_to(admin_domains_url) }
    #  format.xml  { head :ok }
    end
  end
end

app/helpers/admin/domains_helper.rb
module Admin::DomainsHelper
end

app/views/admin/domains/_form.html.erb
<%= form_for([:admin, @domain]) do |f| %>
  <% if @domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% @domain.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :site_id, :value => "Site" %><br />
    <%= f.select :site_id, options_for_select(@site_select, @domain.site_id) %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/domains/edit.html.erb
<h1>Edit domain</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_domains_path %>

app/views/admin/domains/index.html.erb
<h1>Listing domains</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>

<% @domains.each do |domain| %>
  <tr>
    <td><%= domain.name %></td>
    <td><%= link_to 'Show', [:admin, domain] %> |
        <%= link_to 'Edit', edit_admin_domain_path(domain) %> |
        <%= link_to 'Destroy', [:admin, domain], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<%- end -%>
</table>

<br />

<%= link_to 'New Domain', new_admin_domain_path %>

app/views/admin/domains/new.html.erb
<h1>New domain</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_domains_path %>

app/views/admin/domains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @domain.name %>
</p>

<p>
  <b>Active:</b>
  <%= @domain.active %>
</p>


<%= link_to 'Edit', edit_admin_domain_path(@domain) %> |
<%= link_to 'Back', admin_domains_path %>