config/routes.rb
Hydra::Application.routes.draw do
  namespace :admin do
    root :to => 'pages#index'
    resources :domains
    resources :sites
    resources :pages
  end
  get "admin/documents" => "admin/documents#index"
  post "admin/documents/mkdir" => "admin/documents#mkdir"
  post "admin/documents/delete" => "admin/documents#delete"
  post "admin/documents/upload" => "admin/documents#upload"

  get "page/index"

  get "page/error"

  devise_for :users do
    get "/login" => "devise/sessions#new"
    get '/logout', :to => 'devise/sessions#destroy'
    get '/register', :to => 'devise/users#new'
  end
  

  root :to => "page#index"
  
  get "(:page)", :to => "page#index"

end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :domains
  has_many :pages
  has_many :site_users
  has_many :users, :through => :site_users
  default_scope where(:active => true)
  
  def self.current(domain_name = nil)
    site_id = current_id(domain_name)
    return nil if site_id.nil?
    return Site.find(site_id)
  end
  
  def self.current_id(domain_name = nil)
    domain = Domain.where("name = ?", domain_name.downcase).first
    return domain && domain.site_id
  end
  
  def self.backup(site_id)
    site = Site.find(site_id)
    backup_hash = site.to_backup_hash
    backup_data = Base64.encode64(Marshal.dump(backup_hash))
    file_name = "#{Time.now.strftime("%Y%m%d%H%M%S")}.bk"
    dir = File.join(file_name)
    DocumentManager.touch_dir(["backups", site.clean_name])
    file_path = File.join(Rails.root, "backups", site.clean_name , file_name)
    begin
      f = File.open(file_path, "w")
      f.puts backup_data
      f.close
      return File.join(site.clean_name, file_name)
    rescue => err
      puts "Exception: #{err}"
      err
    end
  end
  
  def self.from_backup(file_name)
    file_name = File.join(Rails.root, "backups", file_name)
    begin
      file = File.new(file_name, "r")
      backup_hash = Marshal.load(Base64.decode64(file.read))
      file.close
    rescue => err
      puts "Exception: #{err}"
      err
    end
    from_backup_hash(backup_hash)
  end
  
  def clean_name
    name.gsub(/\s|-/, "_").downcase
  end
  
  def to_backup_hash
    backup_hash = { "site" => {} }
    col_names = Site.column_names - ["id"]
    col_names.each { |col| backup_hash["site"][col] = self.send(col.to_sym ) }
    backup_hash["domains"] = self.domains.collect{ |dom| dom.to_backup_hash }
    backup_hash["pages"] = self.pages.collect{ |page| page.to_backup_hash }
    backup_hash["users"] = self.users.collect{ |user| user.to_backup_hash }
    # will add forms here soon
    # will add form_results here soon
    backup_hash
  end
  
  def self.from_backup_hash(backup_hash)
    site = Site.new(backup_hash["site"])
    if site.save
      backup_hash["domains"].each{|dom_hash| Domain.from_backup_hash(dom_hash, site.id) }
      backup_hash["pages"].each{|page_hash| Page.from_backup_hash(page_hash, site.id) }
      backup_hash["users"].each{|user_hash| Domain.from_backup_hash(user_hash, site.id) }
      # will add forms here soon
      # will add form_results here soon
    else
      raise RuntimeError, "Unable to read/save Site #{site.inspect}"
    end
    true
  end
  
end

app/controllers/admin/sites_controller.rb
class Admin::SitesController < ApplicationController
  before_filter :requires_site_admin_login
  
  # GET /sites
  # GET /sites.xml
  def index
    @sites = Site.all

    respond_to do |format|
      format.html # index.html.erb
      #format.xml  { render :xml => @sites }
    end
  end

  # GET /sites/1
  # GET /sites/1.xml
  def show
    @site = Site.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      #format.xml  { render :xml => @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.xml
  def new
    @site = Site.new

    respond_to do |format|
      format.html # new.html.erb
      #format.xml  { render :xml => @site }
    end
  end

  # GET /sites/1/edit
  def edit
    @site = Site.find(params[:id])
  end

  # POST /sites
  # POST /sites.xml
  def create
    params[:site][:name] = params[:site][:name].downcase
    @site = Site.new(params[:site])

    respond_to do |format|
      if @site.save
        format.html { redirect_to([:admin, @site], :notice => 'Site was successfully created.') }
      #  format.xml  { render :xml => @site, :status => :created, :location => @site }
      else
        format.html { render :action => "new" }
      #  format.xml  { render :xml => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.xml
  def update
    params[:site][:name] = params[:site][:name].downcase
    @site = Site.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to([:admin, @site], :notice => 'Site was successfully updated.') }
    #    format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
     #   format.xml  { render :xml => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.xml
  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to(admin_sites_url) }
    #  format.xml  { head :ok }
    end
  end
end

app/helpers/admin/sites_helper.rb
module Admin::SitesHelper
end

app/views/admin/sites/_form.html.erb
<%= form_for([:admin, @site]) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :layout %><br />
    <%= f.text_field :layout %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :favicon %><br />
    <%= f.text_field :favicon %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @site] %> |
<%= link_to 'Back', admin_sites_path %>

app/views/admin/sites/index.html.erb
<h1>Listing sites</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Active</th>
    <th>Actions</th>
    <th></th>
    <th></th>
  </tr>

<% @sites.each do |site| %>
  <tr>
    <td><%= site.name %></td>
    <td><%= site.active %></td>
    <td><%= link_to 'Show', [:admin, site] %> |
        <%= link_to 'Edit', edit_admin_site_path(site) %> |
        <%= link_to 'Destroy', [:admin, site], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Site', new_admin_site_path %>

app/views/admin/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_sites_path %>

app/views/admin/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @site.name %>
</p>

<p>
  <b>Active:</b>
  <%= @site.active %>
</p>


<%= link_to 'Edit', edit_admin_site_path(@site) %> |
<%= link_to 'Back', admin_sites_path %>